apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jNjN3Y3U4NGlwYmoudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db_username: admin
  db_password: Cloud123
